### ISSUE TITLE
Problem with matlab

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-superbuild#107]
> Hi, i am having problem with MATLAB simulations. I am getting error like:
failed assertion in b:\matlab\toolbox\stateflow\src\stateflow\utils\object.cpp at line 2853:
object[id]!=NULL

> I looked into the post dated 29th Jan 2015 Memory allocation error with holder block #69
> but dont understand how to rectify this.

> Please help!

Hi @garimaiitd, can you provide more information on your problem. 
In particular it would be nice to know:
 * Operating System
 * Matlab Version
 * Which Matlab code or Simulink model are you using

Thanks!

**Comment by garimaiitd** [comment]
- Operating System: WINDOWS 7
   - Matlab Version: MATLAB R2013b
   - Which Matlab code or Simulink model are you using: I am trying to
   simulate one simevents model given on the Mathworks site "
   http://blogs.mathworks.com/simulink/2015/02/04/surprising-results-from-modeling-queues-with-simevents/
   "

Thanks.

-Garima

On Fri, Feb 12, 2016 at 3:52 PM, Silvio Traversaro <notifications@github.com
> wrote:

> Hi, i am having problem with MATLAB simulations. I am getting error like:
> failed assertion in
> b:\matlab\toolbox\stateflow\src\stateflow\utils\object.cpp at line 2853:
> object[id]!=NULL
>
> I looked into the post dated 29th Jan 2015 Memory allocation error with
> holder block #69
> <https://github.com/robotology/codyco-superbuild/issues/69>
> but dont understand how to rectify this.
>
> Please help!
>
> Hi @garimaiitd <https://github.com/garimaiitd>, can you provide more
> information on your problem.
> In particular it would be nice to know:
>
>    - Operating System
>    - Matlab Version
>    - Which Matlab code or Simulink model are you using Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robotology/codyco-superbuild/issues/107>.
>



-- 
Take time to laugh, for it is
the music of the soul.

**Comment by francesco-romano** [comment]
Hi @garimaiitd 

If I understood correctly you are trying to simulate a model provided by Mathworks.
I don't know how this can be related to the software provided by us.

I think you should ask directly to Mathwork support. I doubt we can provide any.

**Comment by garimaiitd** [comment]
ok. Thanks for your time and prompt response .

On Fri, Feb 12, 2016 at 4:04 PM, Francesco Romano <notifications@github.com>
wrote:

> Hi @garimaiitd <https://github.com/garimaiitd>
>
> If I understood correctly you are trying to simulate a model provided by
> Mathworks.
> I don't know how this can be related to the software provided by us.
>
> I think you should ask directly to Mathwork support. I doubt we can
> provide any.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robotology/codyco-superbuild/issues/107#issuecomment-183265002>
> .
>



-- 
Take time to laugh, for it is
the music of the soul.
