### ISSUE TITLE
Enable Ocra software by default on OS X and Linux

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-superbuild#108]
Hi @robotology/codyco-developers , 
  thanks to the work of  @ahoarau and @rlober the OCRA software by ISIR is now compiling smoothly on both Linux and OS X . 

I am therefore inclined to enable by default the `CODYCO_BUILD_OCRA_MODULES` CMake option on the `codyco-superbuild`. While this will increase the build time of the superbuild for all users (but we have several "unused" software/repo that we can remove from the superbuild to reduce its build time) I think it is necessary to reduce the friction in using the OCRA software promote the software integration in the CoDyCo project. 

Comments on this are welcome.

**Comment by rlober** [comment]
Closing based on: https://github.com/robotology/codyco-superbuild/pull/156
