### ISSUE TITLE
New version of WB-Toolbox : 2.0 

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-superbuild#114]
Hi everyone @robotology/codyco-developers @azadm @hu-yue @serena-ivaldi @robertocalandra @misaki43 @serena-ivaldi

   thanks to the hard work of @francesco-romano, @jeljaik, @gabrielenava  and @DanielePucci we have released a new version of the WBI-Toolbox, the [WB-Toolbox 2.0](https://github.com/robotology/WB-Toolbox) ( notice that we dropped the **I** in the name of the new version). 

The WB-Toolbox 2.0 is a refined and cleaned up version of the WBI-Toolbox, that is both easier to use and to modify. We had to do non-backward compatible changes, so both the new WB-Toolbox 2.0 and the old WBI-Toolbox 1.0 can be installed side by side in the same superbuild. 
In particular the WB-Toolbox 2.0 compilation is enabled in the superbuild by setting to on the `CODYCO_USES_MATLAB` CMake option, while the `CODYCO_USES_WBI_TOOLBOX` CMake option enables the compilation of the old WBI-Toolbox 1.0 . For more on options to enable Matlab-dependent software on the superbuild, please check the [relevant section on the codyco-superbuild README](https://github.com/robotology/codyco-superbuild#matlab-software).

The old WBI-Toolbox 1.0 will be removed by the master branch of the `codyco-superbuild` on **June 1st 2016**, so it is strongly recommended to migrate your Simulink models to the new WB-Toolbox 2.0 as soon as possible, following the [Migration guide on the WB-Toolbox 2.0 repository](https://github.com/robotology/WB-Toolbox/blob/master/doc/Migration.md). 

The controllers implemented by IIT using the WB-Toolbox have been already been migrated in https://github.com/robotology-playground/WBI-Toolbox-controllers/commit/535c5e1b78d0a242609d07cf6aec3449f2b42994 . 

As mentioned before, the new WB-Toolbox 2.0 is also easier to extend. To see how to add a new block to the WB-Toolbox , please check the [developers documentation of WB-Toolbox](https://github.com/robotology/WB-Toolbox/blob/master/README.md#modifying-the-toolbox).

Thanks for the attention, and feel free to open an issue on [WB-Toolbox issue tracker](https://github.com/robotology/WB-Toolbox/issues/new) for any problem you may encounter or question you may need to ask.

**Comment by francesco-romano** [comment]
cc @claudia-lat
