### ISSUE TITLE
Tasks for the third year review meeting demo

### ISSUE THREAD

**Issue by DanielePucci** [robotology/codyco-superbuild#116]
The third year review meeting will include also an experimental validation of the designed controllers. To this purposes, we - as IIT guys - are planning to show the following demos:

D1. iCub balancing on a soft carpet;
D2. iCub balancing on seesaws.

For the success of the above validations, the following tasks have been identified (the responsible of each task is listed after the task itself):
- [x] T1: Generate the model for iCub Darmstadt01 @traversaro 
- [ ] T2: Investigate quality of joint velocities from High Resolution Encoders @DanielePucci
- [ ] T3: Tool for Offset / C.M. FT sensors calibration @fjandrad
- [ ] T4: Tool for fine encoders offsets calibration from accelerometers @nunoguedelha @naveenoid 
- [ ] T5: Use the IMUs attached to the feet and Base (waist)
  Mechanical : where and how do we attach them? (contact: Tisi)
  Software: what about the driver? (contact: Accame)
  Tests @traversaro @francesco-romano @DanielePucci
- [ ] T6 :Generating joint references compatible with CoM trajectories @francesco-romano 
- [x] T7: WholeBodyDynamicsTree on PC104 @traversaro 
- [ ] T8: Controller re-design @DanielePucci
- [ ] T9: Carpet stiffness estimation

@robotology/codyco-developers @azadm @hu-yue @serena-ivaldi @robertocalandra @misaki43 @serena-ivaldi

**Comment by traversaro** [comment]
CoDyCo Deliverable 5.3 (available at https://github.com/robotology-playground/codyco-deliverables/blob/master/D5.3/pdf/D5.3.pdf) contains some details on the demonstraiton scenario.

**Comment by DanielePucci** [comment]
Task 2) assigned to @TeoKa and me.

**Comment by DanielePucci** [comment]
Expected deadlines and status:

1. Done

2. 28th April: current status, 0%

3. 13th May: current status, 30%

4. 13th May: current status, 35%

5. Cancelled

6. 6th May: current status, 25%

7. 28th April: current status, 50% (but nobody should know it)

8. 13th May, current status, 50%

9. 13th May, current status, 50%

**Comment by DanielePucci** [comment]
The task T8 has the following sub-tasks:
- [ ] general cleaning adding comments of YOGA++ code;
- [ ] avoid the use of two different QPs for finding the control solutions associated with the one-foot and two-feet standing phase;
- [ ] add QP solver to the `balancingControllerOnSeesaw`
- [ ] add a feature to `balancingControllerOnSeesaw` so that to use the robot's IMU to retrive the seesaw orientation and velocity
- [ ] add the continuity constraint of torques to  `balancingControllerOnSeesaw`
- [ ] add the continuity constraint of torques to  `balancingController`
- [ ] add control of seesaw orientation to `balancingControllerOnSeesaw`
- [ ] modify `balancingController` so that to take into account compliant contacts

**Comment by francesco-romano** [comment]
Given that the 3rd year meeting took place some months ago, I close this issue.
