### ISSUE TITLE
Document things to check on the real robot before performing whole body torque control experiments 

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-superbuild#118]
The relevant document to fill is https://github.com/robotology/codyco-superbuild/blob/master/doc/icub-whole-body-torque-control-faqs.md . 

@misaki43 Can you take care of filling this document using the notes that you took? You can modify that document by  opening a Pull Request ( https://help.github.com/articles/using-pull-requests/ ) on this repo. 

The document uses the Markdown format (for a tutorial see here: http://www.markdowntutorial.com), and once you edit it (and the Pull Request is merged in the repo) all the users will see the document at http://wiki.icub.org/codyco/dox/html/index.html .

**Comment by traversaro** [comment]
cc @serena-ivaldi @DanielePucci

**Comment by traversaro** [comment]
Could it make sense to keep in `whole-body-controllers`?

**Comment by gabrielenava** [comment]
Yes, in the [doc](https://github.com/robotology/whole-body-controllers/tree/master/doc) folder. I can move the document there.

**Comment by traversaro** [comment]
Great, I think it can also address https://github.com/robotology/codyco-superbuild/issues/155 .

**Comment by gabrielenava** [comment]
done with https://github.com/robotology/codyco-superbuild/commit/83704ec5c9898fa26c7ceb2d9380da29e4c9e52c

**Comment by gabrielenava** [comment]
I think we can close this issue.
