### ISSUE TITLE
Add info about built projects into README.md

### ISSUE THREAD

**Issue by francesco-romano** [robotology/codyco-superbuild#13]
I think we should add a section in the `README.md` file in which we describe which package we build (and the link to the corresponding repository).

At the same time we should add in each sub-repository the list of the dependencies in case someone does not want to use the superbuild build system.
Also we should enable travis for each sub-repository.

**Comment by traversaro** [comment]
We kind of did this for `robotology-superbuild`'s README. See also the related issue https://github.com/robotology/robotology-superbuild/issues/46 .
