### ISSUE TITLE
compile errors about iKin not found

### ISSUE THREAD

**Issue by serena-ivaldi** [robotology/codyco-superbuild#139]
Dear all,
I am installing a fresh machine (I just git pulled and installed yarp and icub-main without errors) but I have the following errors when compiling  the codyco-superbuild:

> [ 66%] Performing build step for 'WBToolbox'
> [  4%] Building CXX object toolbox/CMakeFiles/WBToolbox.dir/src/InverseKinematics.cpp.o
> /home/icub/software/src/codyco-superbuild/main/WBToolbox/toolbox/src/InverseKinematics.cpp:8:31: fatal error: iCub/iKin/iKinFwd.h: No such file or directory
>  #include <iCub/iKin/iKinFwd.h>
>                                ^
> compilation terminated.
> make[5]: *** [toolbox/CMakeFiles/WBToolbox.dir/src/InverseKinematics.cpp.o] Error 1
> make[4]: *** [toolbox/CMakeFiles/WBToolbox.dir/all] Error 2
> make[3]: *** [all] Error 2
> make[2]: *** [main/WBToolbox/CMakeFiles/YCMStamp/WBToolbox-build] Error 2
> make[1]: *** [CMakeFiles/WBToolbox.dir/all] Error 2
> make: *** [all] Error 2

Using iKin works in other programs, e.g. tutorials. Any idea how to fix it?

I don't know if it can help, but I have this warnings in the ccmake:

 

> CMake Warning (dev) at build/CMakeFiles/YCMEPHelper.cmake:164 (message):
>    YCM_BOOTSTRAP HASH mismatch
> 
>      for file:
>  [/home/icub/software/src/codyco-superbuild/cmake/IncludeUrl.cmake]
>        expected hash: [20835806b1ccb6950c8d235f86c16c938064a4d4]
>          actual hash: [5faefc77acbbe7314d1ddd4560dd48b0eef291c5]
> 
>    Perhaps it is outdated or you have local modification.  Please consider
>    upgrading it, or contributing your changes to YCM.
> 
>  Call Stack (most recent call first):
>    build/CMakeFiles/YCMEPHelper.cmake:1342 (_ycm_hash_check)
>    cmake/YCMBootstrap.cmake:106 (ycm_bootstrap)
>    CMakeLists.txt:84 (include)
>  This warning is for project developers.  Use -Wno-dev to suppress it.

Thanks in advance

**Comment by traversaro** [comment]
This should have been fixed by https://github.com/robotology/codyco-superbuild/issues/139 . 
Please update the superbuild (see https://github.com/robotology/codyco-superbuild#update ) and try again to compile.
