### ISSUE TITLE
Superbuild compilation using YCM boostrap failing (only on new installations)

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-superbuild#143]
See https://travis-ci.org/robotology/codyco-superbuild/builds/144386062 .

cc @mbrunettini Apparently is not just a Jenkins problem.

**Comment by traversaro** [comment]
I am unable to reproduce the issue :/

**Comment by traversaro** [comment]
Apparently it was a temporary failure, probably due to some server that is down : https://travis-ci.org/robotology/codyco-superbuild/jobs/144386063 .

**Comment by mbrunettini** [comment]
We had similar problems with sourceforge. issue now solved.
