### ISSUE TITLE
Do not install mexWholeBodyModel when CODYCO_USES_MATLAB is on

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-superbuild#163]
mexWholeBodyModel  is used by few users and is now a huge repo. We should not install it when a users select `CODYCO_USES_MATLAB`. 

cc @francesco-romano @DanielePucci @iron76 @Ganimed @gabrielenava

**Comment by gabrielenava** [comment]
fixed in this PR https://github.com/robotology/codyco-superbuild/pull/164
