### ISSUE TITLE
codyco-isir repository added to the codyco-superbuild

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-superbuild#17]
@mingxing-liu @rlober @darwinlau 
I have added the codyco-isir repository https://github.com/robotology-playground/codyco-isir to the codyco-superbuild.
 It should be downloaded by default, and you can disable compilation of software that depend on Eigen 3.2.0 setting to off the CODYCO_USES_EIGEN_320 cmake variable, as explained in the installation guide. Let me know if you are able to get the superbuild working. You have write access to both the codyco-superbuild and (obviously) to the codyco-isir repository, feel free to fix any issue or bugs that you find.

**Comment by azadm** [comment]
I haven't managed to install `codyco-isir` with `codyco-superbuild`:

Here is the error that I get:

````
-- checking for module 'eigen_lgsm'
--   package 'eigen_lgsm' not found
CMake Error at /Users/azadm/Documents/codyco-superbuild/build/install/share/YCM/cmake-next/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /Users/azadm/Documents/codyco-superbuild/build/install/share/YCM/cmake-next/Modules/FindPkgConfig.cmake:501 (_pkg_check_modules_internal)
  modules/ISIRWholeBodyController/CMakeLists.txt:23 (PKG_CHECK_MODULES)


-- Configuring incomplete, errors occurred!
See also "/Users/azadm/Documents/codyco-superbuild/build/main/codyco-isir/CMakeFiles/CMakeOutput.log".
make: *** [/Users/azadm/Documents/codyco-superbuild/build/main/codyco-isir/CMakeFiles/YCMStamp/Release/codyco-isir-configure] Error 1
Command /bin/sh failed with exit code 2

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution CMake\ Rules build/codyco-superbuild.build/Release/codyco-isir.build/Script-AE8CC7E89F914AF48769B9D3.sh
(1 failure)
````

I turn on the flag `CODYCO_BUILD_ISIR_MODULES` while making `codyco-superbuild` project. Is it how it should be installed?

**Comment by traversaro** [comment]
cc @rlober

**Comment by rlober** [comment]
@azadm @traversaro 

You will have to wait a day or two or four before you can build codyco-isir. We are working on getting the necessary source code for the lib dependencies on github. I still need to migrate codyco-isir to use this new build but this will take a couple of days. For now set the superbuild cmake options:
`build codyco-isir`  to `NO`
and
`uses eigen 320` to `YES`.

I will let everyone know when the repo is ready and we will update codyco-superbuild accordingly. 

I know this isn't the best of responses but bear with me for a couple of days and you will be able to experience the full glory of the codyco-isir controller!!!!!!
