### ISSUE TITLE
Motor Identification Script for the iCub

### ISSUE THREAD

**Issue by asutcl** [robotology/codyco-superbuild#171]
Hi @francesco-romano,

Any news on the identification script for the iCub as discussed in robotology/QA#204 ?

Thanks!

@serena-ivaldi

**Comment by francesco-romano** [comment]
Hi @asutcl.
We are currently working on it.
I think some basic version will be available at the beginning of June.
You can follow the discussion on this issue: https://github.com/S-Dafarra/torque-control-params-estimation/issues/1

Please, refer to that repository (and its [main fork](https://github.com/robotology-playground/torque-control-params-estimation)) for other questions.
