### ISSUE TITLE
Travis failure on Linux

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-superbuild#172]
See https://travis-ci.org/robotology/codyco-superbuild/builds/230186141 . 

FYI @diegoferigo .

**Comment by traversaro** [comment]
The problem is in `ocra-wbi-plugins` now depends on GUROBI: 
~~~
CMake Error at /home/travis/build/robotology/codyco-superbuild/build/install/share/YCM/cmake-next/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find GUROBI (missing: GUROBI_LIBRARY GUROBI_CXX_LIBRARY
  GUROBI_INCLUDE_DIR)
~~~

@rlober @jeljaik Given the problems related to installing GUROBI on Travis, I think I am going to disable compilation of ocra software in the codyco-superbuil Travis, what do you think?

**Comment by jeljaik** [comment]
My bad! ☝️There's only one client needing Gurobi, it's not the entire library. I'll put the corresponding cmake flag once I get home (Colombia) and merge accordingly. Sorry for the hiccup!

**Comment by traversaro** [comment]
Ok man, thanks!

**Comment by rlober** [comment]
@jeljaik 

You have a chance to fix this yet, or you want me to do it?

**Comment by jeljaik** [comment]
I'm on it :)

**Comment by rlober** [comment]
Gracias amigo ! This will be our first commit from Colombia

**Comment by jeljaik** [comment]
Alright guys, for linux at least it's fixed. I checked directly in travis and merged with the `master` branch of `ocra-wbi-plugins` but I didn't activate it yet in `codyco-superbuild` 

What's missing to solve is the Eigen thingy... I'm gonna try to play with the submodules and see how it goes. 

![image](https://cloud.githubusercontent.com/assets/5030039/26212743/2bbcb8c4-3bbc-11e7-975d-cc35af5ac490.png)

**Comment by rlober** [comment]
:+1:

**Comment by diegoferigo** [comment]
Any news on the ocra build status? @jeljaik @rlober

**Comment by jeljaik** [comment]
We're working on separate forks of `ocra-recipes` and `ocra-wbi-plugins` to completely remove `Eigen-LGSM`.

**Comment by traversaro** [comment]
Closing due to https://github.com/robotology/codyco-superbuild/issues/198 .
