### ISSUE TITLE
CMake's CODYCO_USES_WB_TOOLBOX variable

### ISSUE THREAD

**Issue by diegoferigo** [robotology/codyco-superbuild#184]
This variable is not set anywhere, but used in [BuildWBToolbox.cmake](https://github.com/robotology/codyco-superbuild/blob/master/cmake/BuildWBToolbox.cmake#L14). Can we remove it? I'm probably missing something, but it doesn't seem it has any effect in the `CMAKE_CACHE_ARGS` passed by `ycm_ep_helper`.

The `WB-Toolbox` repo is already turned on by [`CODYCO_USES_MATLAB`](https://github.com/robotology/codyco-superbuild/blob/master/CMakeLists.txt#L132).

cc @traversaro @francesco-romano @gabrielenava

**Comment by traversaro** [comment]
I think it is just a leftover of the ancient past. I am ok with removing it.

**Comment by traversaro** [comment]
Also `CODYCO_TRAVIS_CI` is unused in WB-Toolbox https://github.com/robotology/WB-Toolbox/search?utf8=%E2%9C%93&q=CODYCO_TRAVIS_CI&type= , so we can safely remove it as well.

**Comment by traversaro** [comment]
The `robotology-superbuild'`s https://github.com/robotology/robotology-superbuild/blob/master/cmake/BuildWBToolbox.cmake is not affected by this problem.
