### ISSUE TITLE
Compilation fails with `CODYCO_USES_OROCOS_BFL_BERDY flag On

### ISSUE THREAD

**Issue by prashanthr05** [robotology/codyco-superbuild#195]
I get missing header files (like LeggedOdometry.h, yarpWholeBodyInterface.h,..) error during compilation if I turn on the flag `CODYCO_USES_OROCOS_BFL_BERDY` on. Compilation is successful, with the flag Off

**Comment by traversaro** [comment]
Fixed as that flag is not available in the new robotology-superbuild.
