### ISSUE TITLE
Visualization tools useful for balancing

### ISSUE THREAD

**Issue by serena-ivaldi** [robotology/codyco-superbuild#20]
We need some graphical visualization tools for balancing experiments.

For example:
- visualizing ZMP, COP, COM, forces
- visualizing torques in main limbs (at least have an idea if we are close to torques_max)
- external forces

Should we integrate those tools in the iCub_GUI? Or make new tools?
Or use matlab?

**Comment by traversaro** [comment]
rviz and (to a much lesser extent) iDynTree visualizer are currently being used for visualization.
Other useful software for robotics visualization are:
* VTK : https://www.vtk.org/
* MeshCat : https://github.com/rdeits/meshcat 
* Vizkit3D : https://www.rock-robotics.org/stable/documentation/graphical_user_interface/450_vizkit3d.html 

Closing as this issue stopped being useful for brainstorming several years ago.
