### ISSUE TITLE
Context file of WBI-Toolbox not properly installed on first superbuild make

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-superbuild#28]
The problem does not appear after the second superbuild make. Probably worth adding a check on travis. 

cc @hu-yue

**Comment by francesco-romano** [comment]
This issue is quite old and a lot of code has been changed in the meanwhile.

Closing for now. Reopen if still present.

**Comment by francesco-romano** [comment]
I managed to replicate again the issue, even if in a slightly different way.
No matter how many times, building the super build did not create the share folder.
I had to manually install the WBI-Toolbox subproject.
As a side note: the superbuild did not updated the cmake cache in the subproject (or something similar) 

cc @traversaro @drdanz

**Comment by traversaro** [comment]
The issue is now solved?

**Comment by francesco-romano** [comment]
I did not notice this problem anymore.
If it happens again we can reopen the issue

**Comment by traversaro** [comment]
:+1:
