### ISSUE TITLE
Document on how to update the superbuild using XCode in the README.md 

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-superbuild#48]
I guess that @francesco-romano , @nunoguedelha or @iron76 can address this. 

cc @azadm

**Comment by francesco-romano** [comment]
Everything is already documented in YCM documentation:
http://robotology.github.io/ycm/gh-pages/master/manual/ycm-superbuild.7.html#os-x

**Comment by traversaro** [comment]
Perfect, we have to had a link to it in our readme then.

**Comment by drdanz** [comment]
Feel free to improve the YCM documentation :smile:
