### ISSUE TITLE
Various maintenance tasks for all subprojects 

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-superbuild#49]
There are several tasks that should be done for all subprojects of the superbuild, for which we need volunteers ( : ) ). This tasks are also a good way of getting in touch with all the codebase and all the build system) : @naveenoid  @nunoguedelha @rbonghi . 
- [ ] Migrate all print of yarp related library/modules (mainly in yarp-wholebodyinterface, codyco-modules and WBI-Toolbox) to the new yDebug/yInfo yarp macros (similarly to what @randaz81 did in https://github.com/robotology/icub-main/commit/c89def02c9094a0d008a1077e24521232e69c13b ). This would enable a much easier reading of output of complex setup using the new yarp-logger . 
  Subprojects to update (feel free to add):
  - [ ] codyco-modules 
  - [x] yarp-wholebodyinterface
  - [x] WBI-Toolbox
  - [x] paramHelp 
  - [x] codyco-commons
  - [x] gazebo-yarp-plugins (this is a specific case, discussed in https://github.com/robotology/gazebo-yarp-plugins/issues/87, basically we need to move some outputs to yarp log macros and some to gazebo log macros) 
- [x] Fix travis on all subprojects. Travis is a really useful continuous integration tool for validating that no commit break the build of a given project. The major problem for the subprojects is to deal with dependencies, but we can rely on the superbuild for that (see what I did in iDynTree for an example : https://github.com/robotology-playground/idyntree/pull/15m, on in codyco-modules in https://github.com/robotology/codyco-modules/commit/6c1d5dc126e995e23fc0571845164fe5f6be2788 and the following commits ) 
  Subprojects to update (feel free to add):
  - [x] codyco-modules 
  - [x] wholebodyinterface
  - [x] yarp-wholebodyinterface
  - [x] codyco-commons

**Comment by naveenoid** [comment]
I can do the first task for codyco-modules and yarp-wholebodyinterface and maybe WBI-Toolbox.

**Comment by traversaro** [comment]
@naveenoid coffee allocated!

**Comment by nunoguedelha** [comment]
I'll be dealing with the "paramHelp" and "codyco-commons" modules

**Comment by jeljaik** [comment]
Done for WBI-Toolbox as in: https://github.com/robotology-playground/WBI-Toolbox/commit/7384d1d3e3c8951b6ecc8b198bbb51f2108226cc

**Comment by nunoguedelha** [comment]
Going for 2nd task (Travis fix) regarding wholebodyinterface and yarp-wholebodyinterface

**Comment by traversaro** [comment]
`codyco-modules` will soon be deprecated, except for a few devices. Closing the issue here as it is not useful anymore.
