### ISSUE TITLE
Coding conventions that "serialize" dynamics notation

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-superbuild#53]
@jeljaik @naveenoid 
You had the same idea! Here the issue to implement it. : )

**Comment by naveenoid** [comment]
I guess the 4 main points to start off this discussion :
1. subscripts and superscripts - using latex like convention but starting
at the most superscripted character and using underscores for the rest :
eg. w_T_b
2. Greek symbols : using english names of symbols like omega.
3. Treating subscripted symbols like joint velocity as qj(double character)
or as q_j(using rule 1 above).
4. As always, matrixes in capitals, vectors non capitalised.


---
Naveen Kuppuswamy, PhD
Post-doctoral Fellow,
Cognitive Humanoids Lab,
Department of Robotics, Brain and Cognitive Sciences (RBCS),
Istituto Italiano di Tecnologia, Genova, Italy

On Fri, Feb 6, 2015 at 12:14 PM, Silvio Traversaro <notifications@github.com

**Comment by traversaro** [comment]
I think this is a good idea, but it is each project documentation duty to define this.
