### ISSUE TITLE
RPC Calib on WholeBodyDynamicsTree fails

### ISSUE THREAD

**Issue by rueckert** [robotology/codyco-superbuild#76]
with 

[INFO]wholeBodyDynamicsTree : calibration for  arms requested 
[INFO] wholeBodyDynamicsThread::calibrateOffset called with code arms
wholeBodyDynamicsThread::decodeCalibCode error: requested feet calibration, but arms FT sensor are not available.
[ERR] wholeBodyDynamicsThread::decodeCalibCode failed

from wholeBodyDynamicsThread.cpp:604 where the arms_fts vector is never set and thus has a zero size. 

@traversaro 

Thank's for your help. Elmar and Alex

**Comment by traversaro** [comment]
Which command are you sending to the `wholeBodyDynamicsTree` rpc?

**Comment by traversaro** [comment]
If you are sending `calib arms`, then I see the bug, as a temporary workaround you can try a `calib all`.

**Comment by rueckert** [comment]
@traversaro Calib all works
