### ISSUE TITLE
Compiling qpOASES_Matlab error with on OsX (10.11)

### ISSUE THREAD

**Issue by iron76** [robotology/codyco-superbuild#84]
Compiling gives the following error:

```
/Applications/MATLAB_R2012b.app/extern/include/tmwtypes.h:819:9: error: unknown type name 'char16_t' 
typedef char16_t CHAR16_T;
```

On possible workaround is proposed here (https://github.com/RobotLocomotion/drake/issues/131). Works for me.

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology-dependencies/qpOASES/commit/6fd1bfa0034e53923e64e80fdf0ff591e19236fd (would be good to bring everything upstream one day : ) ).
